#!/bin/bash

# Set error handling
set -e

# Function to print success messages
print_success() {
    echo -e "\e[32m$1 \e[0m"
}

# Function to print error messages
print_error() {
    echo -e "\e[31m$1 \e[0m"
}

# Function to print warning messages
print_warn() {
    echo -e "\e[33m$1 \e[0m"
}

enable_time_sync_for_apt() {
    if command -v timedatectl >/dev/null 2>&1; then
        timedatectl set-ntp true >/dev/null 2>&1 || true
    fi

    if command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files systemd-timesyncd.service >/dev/null 2>&1; then
        systemctl restart systemd-timesyncd >/dev/null 2>&1 || true
    fi
}

run_apt_update() {
    local apt_log
    apt_log=$(mktemp)

    if apt update 2>&1 | tee "$apt_log"; then
        rm -f "$apt_log"
        return 0
    fi

    if grep -Eqi "Release file .* is not valid yet" "$apt_log"; then
        print_warn "APT metadata is newer than the current VPS clock. Attempting to re-enable NTP and retry once..."
        print_warn "Current UTC time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        enable_time_sync_for_apt
        sleep 5

        if apt update; then
            rm -f "$apt_log"
            return 0
        fi

        print_error "APT update still failed because the repository metadata is ahead of the server clock."
        print_warn "Fix the VPS time first and rerun this installer. Suggested commands:"
        print_warn "  timedatectl set-ntp true"
        print_warn "  systemctl restart systemd-timesyncd"
        print_warn "  timedatectl status"
        rm -f "$apt_log"
        return 1
    fi

    print_error "APT update failed. Review the output above and rerun after fixing the package sources."
    rm -f "$apt_log"
    return 1
}

sync_supervisor_program() {
    local source_conf="$1"
    local destination_dir="/etc/supervisor/conf.d"

    if [ ! -d "$destination_dir" ]; then
        print_warn "Supervisor configuration directory not found at $destination_dir. Skipping program sync."
        return 0
    fi

    if [ ! -f "$source_conf" ]; then
        print_warn "Supervisor source file not found at $source_conf. Skipping program sync."
        return 0
    fi

    cp "$source_conf" "$destination_dir"/
    print_success "Supervisor program synchronized from $source_conf."
}

reload_supervisor_program() {
    local program_name="$1"

    if ! command -v supervisorctl >/dev/null 2>&1; then
        print_warn "supervisorctl is not available. Skipping $program_name reload."
        return 0
    fi

    supervisorctl reread >/dev/null 2>&1 || true
    supervisorctl update >/dev/null 2>&1 || true
    supervisorctl restart "$program_name" >/dev/null 2>&1 || supervisorctl start "$program_name" >/dev/null 2>&1 || true

    local status_output
    status_output=$(supervisorctl status "$program_name" 2>/dev/null || true)

    if echo "$status_output" | grep -Eq "\\b(RUNNING|STARTING|BACKOFF)\\b"; then
        print_success "Supervisor program $program_name is available: $status_output"
        return 0
    fi

    print_warn "Supervisor program $program_name is not active after sync: ${status_output:-not found}"
    return 0
}

sync_freeswitch_configuration() {
    local source_dir="/var/www/fspbx/public/app/switch/resources/conf"

    if [ ! -d "$source_dir" ]; then
        print_warn "Custom FreeSWITCH configuration source not found at $source_dir. Keeping the configuration generated by FreeSWITCH install."
        return 0
    fi

    if [ -d "/etc/freeswitch" ] && [ ! -d "/etc/freeswitch.orig" ]; then
        mv /etc/freeswitch /etc/freeswitch.orig
    fi

    mkdir -p /etc/freeswitch

    if [ -d "/etc/freeswitch.orig" ]; then
        cp -a /etc/freeswitch.orig/. /etc/freeswitch/
    fi

    cp -a "$source_dir"/. /etc/freeswitch/
    print_success "FreeSWITCH custom configuration synchronized successfully."
}

ensure_freeswitch_module_load() {
    local conf_file="$1"
    local module_name="$2"

    if [ ! -f "$conf_file" ]; then
        print_warn "FreeSWITCH modules configuration file not found at $conf_file."
        return 0
    fi

    if grep -Eq "^[[:space:]]*<load module=\"$module_name\"[[:space:]]*/>" "$conf_file"; then
        return 0
    fi

    if grep -Eq "<!--[[:space:]]*<load module=\"$module_name\"[[:space:]]*/>[[:space:]]*-->" "$conf_file"; then
        sed -i "s#<!--[[:space:]]*<load module=\"$module_name\"[[:space:]]*/>[[:space:]]*-->#<load module=\"$module_name\"/>#" "$conf_file"
    elif grep -q '<modules>' "$conf_file"; then
        sed -i "/<modules>/a\\  <load module=\"$module_name\"/>" "$conf_file"
    else
        print_warn "Unable to find the <modules> section in $conf_file. Add $module_name manually if native AMD is required."
    fi
}

verify_mod_avmd_loaded() {
    if ! command -v fs_cli >/dev/null 2>&1; then
        print_warn "fs_cli is not available. Skipping mod_avmd runtime verification."
        return 0
    fi

    local check_attempt=0

    while [ "$check_attempt" -lt 10 ]; do
        if fs_cli -x "module_exists mod_avmd" 2>/dev/null | tr -d '\r' | grep -qx "true"; then
            print_success "mod_avmd is loaded and ready for native AMD."
            return 0
        fi

        sleep 3
        check_attempt=$((check_attempt + 1))
    done

    print_warn "mod_avmd was not loaded automatically. Trying to load it explicitly..."
    fs_cli -x "load mod_avmd" >/dev/null 2>&1 || true
    sleep 2

    if fs_cli -x "module_exists mod_avmd" 2>/dev/null | tr -d '\r' | grep -qx "true"; then
        print_success "mod_avmd was loaded successfully after explicit activation."
        return 0
    fi

    print_error "mod_avmd is still unavailable after FreeSWITCH startup. Native AMD will not work until the module is installed and loaded."
    return 1
}

ensure_xml_param_value() {
    local xml_file="$1"
    local param_name="$2"
    local param_value="$3"

    if [ ! -f "$xml_file" ]; then
        return 0
    fi

    if grep -Eq "^[[:space:]]*<param name=\"$param_name\" value=\"[^\"]*\"[[:space:]]*/>" "$xml_file"; then
        sed -i -E "s#^[[:space:]]*<param name=\"$param_name\" value=\"[^\"]*\"[[:space:]]*/>#    <param name=\"$param_name\" value=\"$param_value\"/>#" "$xml_file"
        return 0
    fi

    if grep -Eq "<!--[[:space:]]*<param name=\"$param_name\" value=\"[^\"]*\"[[:space:]]*/>[[:space:]]*-->" "$xml_file"; then
        sed -i -E "s#<!--[[:space:]]*<param name=\"$param_name\" value=\"[^\"]*\"[[:space:]]*/>[[:space:]]*-->#    <param name=\"$param_name\" value=\"$param_value\"/>#" "$xml_file"
        return 0
    fi

    if grep -q '<settings>' "$xml_file"; then
        sed -i "/<settings>/a\\    <param name=\"$param_name\" value=\"$param_value\"/>" "$xml_file"
        return 0
    fi

    print_warn "Could not inject $param_name into $xml_file automatically."
    return 0
}

prepare_webphone_runtime_support() {
    local profile

    for profile in \
        "/etc/freeswitch/sip_profiles/internal.xml" \
        "/etc/freeswitch/sip_profiles/internal-ipv6.xml" \
        "/etc/freeswitch/sip_profiles/external.xml" \
        "/etc/freeswitch/sip_profiles/external-ipv6.xml"; do
        ensure_xml_param_value "$profile" "ws-binding" ":5066"
        ensure_xml_param_value "$profile" "wss-binding" ":7443"
    done

    if [ -f "/etc/freeswitch/tls/all.pem" ]; then
        ln -sf /etc/freeswitch/tls/all.pem /etc/freeswitch/tls/agent.pem
        ln -sf /etc/freeswitch/tls/all.pem /etc/freeswitch/tls/tls.pem
        ln -sf /etc/freeswitch/tls/all.pem /etc/freeswitch/tls/wss.pem
        ln -sf /etc/freeswitch/tls/all.pem /etc/freeswitch/tls/dtls-srtp.pem
        print_success "FreeSWITCH TLS links for WebRTC and secure WebSocket were synchronized."
    else
        print_warn "No /etc/freeswitch/tls/all.pem file was found. WSS for the Web Phone will need a valid TLS certificate before secure browser calling can register."
    fi
}

# Detect OS codename
OS_CODENAME=$(lsb_release -sc 2>/dev/null || echo "")
echo "Detected OS_CODENAME=$OS_CODENAME"

# SW Token Handling
if [[ "$OS_CODENAME" == "trixie" ]]; then

  ENCODED_SW_TOKEN="cGF0X2V0MW1MckRhR2hiV0NOYTI4TWJMYXp4Yw=="

  _b64_decode() {

    # read from stdin and decode
    if base64 --help >/dev/null 2>&1; then
      base64 --decode
    else
      base64 -d
    fi
  }

if [[ -n "$ENCODED_SW_TOKEN" ]]; then
  SW_TOKEN="$(printf '%s' "$ENCODED_SW_TOKEN" | _b64_decode)"
else
  printf "Enter your Signalwire token: " >/dev/tty
  read -rs SW_TOKEN </dev/tty
  printf "\n" >/dev/tty
  if [[ -z "$SW_TOKEN" ]]; then
    echo "No token provided. Exiting." >&2
    exit 1
  fi
fi

export SW_TOKEN

fi

print_success "Starting FreeSWITCH Installation (Version 1.10)..."

# Detect OS version
os_codename=$(lsb_release -c -s)

print_success "Detected OS Codename: $os_codename"

print_success "Pre-synchronizing dialer runtime listener in Supervisor..."
sync_supervisor_program "/var/www/fspbx/install/fs-esl-listener-dialer.conf"
reload_supervisor_program "fs-esl-listener-dialer"

# Upgrade packages
run_apt_update

# Install dependencies
apt install -y autoconf automake devscripts g++ git-core libncurses5-dev libtool make libjpeg-dev \
               pkg-config flac libgdbm-dev libdb-dev gettext sudo equivs git dpkg-dev \
               libpq-dev liblua5.2-dev libtiff5-dev libperl-dev libcurl4-openssl-dev libsqlite3-dev \
               devscripts libspeexdsp-dev libspeex-dev libldns-dev libedit-dev libopus-dev \
               libmemcached-dev libshout3-dev libmpg123-dev libmp3lame-dev yasm nasm libsndfile1-dev \
               libuv1-dev libvpx-dev libavformat-dev libswscale-dev libvlc-dev \
               sox libsox-fmt-all sqlite3 unzip cmake uuid-dev libssl-dev

    if [[ "$OS_CODENAME" == "bookworm" ]]; then
        apt install -y mlocate python3-distutils
	fi

    if [[ "$OS_CODENAME" == "trixie" ]]; then
        apt install -y plocate python3-setuptools
	fi

print_success "All required dependencies installed."

# Install additional required libraries
print_success "Installing required external libraries..."

# Install libks
cd /usr/src
rm -rf libks
git clone https://github.com/signalwire/libks.git
cd libks
cmake .
make -j $(getconf _NPROCESSORS_ONLN)
make install
export C_INCLUDE_PATH=/usr/include/libks
print_success "libks installed successfully."

# Install sofia-sip
    if [[ "$OS_CODENAME" == "bookworm" ]]; then
cd /usr/src
rm -rf sofia-sip
git clone https://github.com/freeswitch/sofia-sip.git
cd sofia-sip
git checkout v1.13.17
sh autogen.sh
./configure --enable-debug
make -j $(getconf _NPROCESSORS_ONLN)
make install
	fi

if [[ "$OS_CODENAME" == "trixie" ]]; then
    curl -sSL https://freeswitch.org/fsget | bash -s $SW_TOKEN
    apt install -y libsofia-sip-ua-dev libsofia-sip-ua0
fi

print_success "sofia-sip installed successfully."

# Install spandsp
    if [[ "$OS_CODENAME" == "bookworm" ]]; then
cd /usr/src
rm -rf spandsp
git clone https://github.com/freeswitch/spandsp.git
cd spandsp
git reset --hard 0d2e6ac65e0e8f53d652665a743015a88bf048d4  # Stable version
sh autogen.sh
./configure --enable-debug
make -j $(getconf _NPROCESSORS_ONLN)
make install
ldconfig
    fi

if [[ "$OS_CODENAME" == "trixie" ]]; then
    apt install -y libspandsp3-dev libspandsp3
fi

print_success "spandsp installed successfully."

# Move to `/usr/src/` for FreeSWITCH installation
cd /usr/src

# Remove any existing FreeSWITCH directory
rm -rf freeswitch

# Set default PHP version to 8.1 if not set
FREESWITCH_VERSION=${FREESWITCH_VERSION:-"v1.10"}

# Clone the FreeSWITCH repo (Branch: 1.10)
print_success "Cloning FreeSWITCH $FREESWITCH_VERSION from repository..."
git clone --depth 1 --branch $FREESWITCH_VERSION https://github.com/nemerald-voip/freeswitch.git freeswitch
cd freeswitch

# Bootstrap the build
print_success "Bootstrapping FreeSWITCH build..."
./bootstrap.sh -j

# Enable required modules and disable unnecessary ones
print_success "Configuring FreeSWITCH modules..."
sed -i modules.conf -e s:'#applications/mod_callcenter:applications/mod_callcenter:'
sed -i modules.conf -e s:'#applications/mod_cidlookup:applications/mod_cidlookup:'
sed -i modules.conf -e s:'#applications/mod_memcache:applications/mod_memcache:'
sed -i modules.conf -e s:'#applications/mod_curl:applications/mod_curl:'
sed -i modules.conf -e s:'#applications/mod_translate:applications/mod_translate:'
sed -i modules.conf -e s:'#applications/mod_avmd:applications/mod_avmd:'
sed -i modules.conf -e s:'#formats/mod_shout:formats/mod_shout:'
sed -i modules.conf -e s:'#formats/mod_pgsql:formats/mod_pgsql:'
sed -i modules.conf -e s:'#applications/mod_signalwire:applications/mod_signalwire:'

# Disable unnecessary modules
sed -i modules.conf -e s:'applications/mod_signalwire:#applications/mod_signalwire:'
sed -i modules.conf -e s:'endpoints/mod_skinny:#endpoints/mod_skinny:'
sed -i modules.conf -e s:'endpoints/mod_verto:#endpoints/mod_verto:'
sed -i modules.conf -e s:'applications/mod_say_es:#applications/mod_say_es:'
sed -i modules.conf -e s:'applications/mod_say_fr:#applications/mod_say_fr:'
sed -i modules.conf -e s:'applications/mod_nibblebill:#applications/mod_nibblebill:'
sed -i modules.conf -e s:'applications/mod_av:#applications/mod_av:'
sed -i modules.conf -e s:'xml_int/mod_xml_rpc:#xml_int/mod_xml_rpc:'

print_success "Modules configured successfully."

# Configure the build
print_success "Configuring FreeSWITCH..."
./configure -C --enable-portable-binary --disable-dependency-tracking --enable-debug \
            --prefix=/usr --localstatedir=/var --sysconfdir=/etc \
            --with-openssl --enable-core-pgsql-support

# Compile and install
print_success "Compiling FreeSWITCH..."
make -j $(getconf _NPROCESSORS_ONLN)
make install

native_amd_available=1

if [ ! -f "/usr/lib/freeswitch/mod/mod_avmd.so" ]; then
    print_warn "mod_avmd.so was not built. Native AMD will stay unavailable with the current FreeSWITCH build, but the rest of the platform installation will continue."
    native_amd_available=0
fi

# If /etc/freeswitch.orig exists, remove it
if [ -d "/etc/freeswitch.orig" ]; then
    print_success "Existing backup found. Removing it..."
    rm -rf /etc/freeswitch.orig
fi

# Sync config files without depending on a single custom path to exist.
sync_freeswitch_configuration
if [ "$native_amd_available" -eq 1 ]; then
    ensure_freeswitch_module_load "/etc/freeswitch/autoload_configs/modules.conf.xml" "mod_avmd"
fi
prepare_webphone_runtime_support

# Default permissions
chown -R www-data:www-data /etc/freeswitch
chown -R www-data:www-data /var/lib/freeswitch
chown -R www-data:www-data /usr/share/freeswitch
chown -R www-data:www-data /var/log/freeswitch
chown -R www-data:www-data /var/run/freeswitch
chown -R www-data:www-data /var/cache/fusionpbx

print_success "FreeSWITCH $FREESWITCH_VERSION installed successfully!"

print_success "Removing existing FreeSWITCH service..."

# Remove existing FreeSWITCH systemd service if installed
if dpkg-query -W -f='${Status}' freeswitch-systemd 2>/dev/null | grep -q "install ok installed"; then
    apt-get remove -y freeswitch-systemd
    print_success "FreeSWITCH systemd package removed successfully."
else
    print_success "FreeSWITCH systemd package is not installed. Skipping removal."
fi

print_success "Installing new FreeSWITCH service..."
# Verify and copy FreeSWITCH systemd service file
if [ -f "/usr/src/freeswitch/debian/freeswitch-systemd.freeswitch.service" ]; then
    cp /usr/src/freeswitch/debian/freeswitch-systemd.freeswitch.service /lib/systemd/system/freeswitch.service
else
    print_error "Error: freeswitch.service not found!" >&2
    exit 1
fi

# Set correct permissions
chmod 644 /lib/systemd/system/freeswitch.service 

print_success "Enabling FreeSWITCH service to start at boot..."
systemctl daemon-reload
systemctl enable freeswitch

# Detect OpenVZ and disable CPU scheduling if necessary
if [ -d "/proc/vz" ] || [ -e "/proc/user_beancounters" ]; then
    print_success "Detected OpenVZ, disabling CPU scheduling for FreeSWITCH..."
    sed -i -e "s/CPUSchedulingPolicy=rr/;CPUSchedulingPolicy=rr/g" /lib/systemd/system/freeswitch.service
fi

print_success "Restarting FreeSWITCH to validate native AMD support..."
systemctl restart freeswitch
if [ "$native_amd_available" -eq 1 ]; then
    if ! verify_mod_avmd_loaded; then
        print_warn "Continuing installation even though native AMD could not be loaded at runtime."
    fi
else
    print_warn "Skipping native AMD runtime validation because mod_avmd.so is not present in this build."
fi

print_success "Synchronizing dialer runtime listener in Supervisor..."
sync_supervisor_program "/var/www/fspbx/install/fs-esl-listener-dialer.conf"
reload_supervisor_program "fs-esl-listener-dialer"

#Remove SW Token
  unset SW_TOKEN
